### Exemplo de Rede Neural

In [1]:
from time import time
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn import preprocessing
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_predict

In [2]:
wine = pd.read_csv('winequality_red.csv',";")
wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
#Descrição dos dados
dados = wine.values[:, :12]
print("Dataset original:")
print(dados.shape)
wine.head()

Dataset original:
(1599, 12)


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
wine.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [5]:
def index_of_dic(dic, key):
    return dic[key]

def StrList_to_UniqueIndexList(lista):
    group = set(lista)
    
    dic = {}
    i = 0
    for g in group:
        if g not in dic:
            dic[g] = i
            i += 1

    return [index_of_dic(dic, p) for p in lista]

#display(clientes_copia_original.head(12))
display(wine.head(12))

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0             7.4              0.70         0.00             1.9      0.076   
1             7.8              0.88         0.00             2.6      0.098   
2             7.8              0.76         0.04             2.3      0.092   
3            11.2              0.28         0.56             1.9      0.075   
4             7.4              0.70         0.00             1.9      0.076   
5             7.4              0.66         0.00             1.8      0.075   
6             7.9              0.60         0.06             1.6      0.069   
7             7.3              0.65         0.00             1.2      0.065   
8             7.8              0.58         0.02             2.0      0.073   
9             7.5              0.50         0.36             6.1      0.071   
10            6.7              0.58         0.08             1.8      0.097   
11            7.5              0.50         0.36             6.1      0.071   

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  11.0                  34.0   0.9978  3.51       0.56   
1                  25.0                  67.0   0.9968  3.20       0.68   
2                  15.0                  54.0   0.9970  3.26       0.65   
3                  17.0                  60.0   0.9980  3.16       0.58   
4                  11.0                  34.0   0.9978  3.51       0.56   
5                  13.0                  40.0   0.9978  3.51       0.56   
6                  15.0                  59.0   0.9964  3.30       0.46   
7                  15.0                  21.0   0.9946  3.39       0.47   
8                   9.0                  18.0   0.9968  3.36       0.57   
9                  17.0                 102.0   0.9978  3.35       0.80   
10                 15.0                  65.0   0.9959  3.28       0.54   
11                 17.0                 102.0   0.9978  3.35       0.80   

    alcohol  quality  
0       9.4        5  
1       9.8        5  
2       9.8        5  
3       9.8        6  
4       9.4        5  
5       9.4        5  
6       9.4        5  
7      10.0        7  
8       9.5        7  
9      10.5        5  
10      9.2        5  
11     10.5        5

In [6]:
# Atributos e classes
X = wine.iloc[:, 0:10]
y = wine.iloc[:,11]

In [7]:
print(y)

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64


In [8]:
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE().fit_resample(X, y)

In [9]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size = 0.30)  

In [10]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)  

In [11]:
print(X_test)

[[ 1.51772473e+00  1.08597404e-01  1.74175035e+00 ...  7.57379745e-01
  -7.06018768e-01  2.27082149e-01]
 [ 1.69036237e-02 -8.70444082e-01  1.27398447e+00 ...  7.57654428e-01
  -1.74773419e+00  2.59532101e+00]
 [ 1.52561474e+00 -6.97732992e-01  1.43442382e+00 ...  5.73545191e-01
  -1.04462267e+00  6.00535208e-04]
 ...
 [-6.40363513e-01 -3.68647978e-02 -1.30935106e+00 ... -7.56956072e-01
   3.07706964e-01 -4.05956295e-01]
 [-1.27638505e-01  3.28533226e+00 -8.71796760e-01 ... -4.63794024e-01
   7.12105957e-01 -1.37625738e+00]
 [ 1.04160138e+00 -9.41309229e-01  6.72993872e-01 ...  1.27772201e+00
  -5.32507351e-01  1.56825206e+00]]


# Exemplo de cross-validation

In [12]:
#Armazena as predicões
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split  
from imblearn.over_sampling import SMOTE


mlp = MLPClassifier(activation='tanh', hidden_layer_sizes=(250, 400, 250), max_iter=2000, momentum=0.8)

# podemos alterar o activation, layers, iterações e o momentum
mlp.fit(X_train, y_train.values.ravel()) 

predictions = cross_val_predict(mlp,X_resampled,y_resampled,cv=10)
#Calcula acurácia do treino
print("acurácia do treino")
print(accuracy_score(y_resampled,predictions)*100)

#Gera a matriz de confusão do treino
print("matriz de confusão")
print(confusion_matrix(y_resampled,predictions))
#Gera a matriz de confusão do test
print("Report")
print(classification_report(y_resampled,predictions,zero_division=0))

acurácia do treino
79.00146842878121
matriz de confusão
[[678   1   2   0   0   0]
 [  6 643  17  14   1   0]
 [ 17  63 321 226  43  11]
 [ 12  29 201 304 102  33]
 [  0   4  11  26 623  17]
 [  0   0   2   9  11 659]]
Report
              precision    recall  f1-score   support

           3       0.95      1.00      0.97       681
           4       0.87      0.94      0.90       681
           5       0.58      0.47      0.52       681
           6       0.53      0.45      0.48       681
           7       0.80      0.91      0.85       681
           8       0.92      0.97      0.94       681

    accuracy                           0.79      4086
   macro avg       0.77      0.79      0.78      4086
weighted avg       0.77      0.79      0.78      4086

