# Universidade de Caxias do Sul
### Área de Exatas e Engenharias
### Disciplina: Inteligência Computacional
### Profa. Carine G. Webber


## 1. Importação das Classes

In [2]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

## 2. Definição do conjunto de dados de treino e teste

In [3]:
X_treino=[  [1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
         ]
y_treino=[1, 
          1,
          1,
          0
          ]
X_teste=X_treino
y_teste=y_treino

# 3. Exemplo usando o modelo Perceptron
### método de treino => fit(dados_treino,classes_treino)
### método de teste => predict(classes_teste)

In [4]:
ptn = Perceptron(max_iter=500,tol=0.001)                    
ptn.fit(X_treino, y_treino)                    
y_pred=ptn.predict(X_teste)                      
print(y_pred)                                                         

[1 1 1 0]


# 4. Cálculo da acurácia do classificador Perceptron

In [5]:
accuracy=metric.accuracy_score(y_teste, y_pred, normalize=True)
print('acurácia=',accuracy)      

acurácia= 1.0


## Ponto de intersecção : intercept_
## Pesos das conexões : coef_

In [6]:
print(ptn.intercept_, ptn.coef_) 

[-1.] [[2. 2.]]


# 5. Uso de uma Rede Neural Perceptron Multi-camadas (MLP)
## Classe : MLPClassifier
### Parâmetros: 
#### Solver
#### Camadas escondidas
#### Função de ativação


In [7]:
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(1,1), activation='logistic') 
mlp.fit(X_treino, y_treino)                        
y_pred=mlp.predict(X_teste)                        
print(y_pred)                                    
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)                      

[1 1 1 0]
acuracy= 1.0


## 6. Verifique os pesos das conexões entre os neurônios
#### Observe que a cada execução do passo 5, os pesos mudam.

In [8]:

print([coef.shape for coef in mlp.coefs_])  
mlp.coefs_                                 

[(2, 1), (1, 1), (1, 1)]


[array([[4.14760407],
        [4.1564221 ]]), array([[8.13253145]]), array([[14.87565758]])]

# 7. TAREFAS 

- a) modifique os dados (X_treino, y_treino, X_teste)
- b) altere dos dados de binários para bipolares {-1, +1}
- c) altere a camada escondida do MLP: número de camadas (int) ou tamanho (n,m)
- d) altere o parâmetro solver do MLP: {'lbfgs', 'sgd', 'adam'}
- e) altere a função de ativação do MLP: {'identity', 'logistic', 'tanh', 'relu'}, default 'relu'

Orientação:
 - verifique a acurácia de cada predição


# Primeira tarefa: OU Bipolar
Troque as entradas {0, 1} por valores bipolares {-1, +1}. 
Utilize os dados e execute o Perceptron e o MLP, conforme o exemplo (4).

In [10]:
X_treino=[[1, 1], 
            [1, -1],
            [-1, 1],
            [-1, -1]
           ]
y_treino=[1, 
            1,
            1,
            -1
           ]
X_teste=X_treino
y_teste=y_treino

ptn = Perceptron(max_iter=500,tol=0.001)                    
ptn.fit(X_treino, y_treino)                    
y_pred=ptn.predict(X_teste)                      
print(y_pred) 
accuracy=metric.accuracy_score(y_teste, y_pred, normalize=True)
print('acurácia Perceptron:',accuracy)    
print()

mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(3,3), activation='relu') 
mlp.fit(X_treino, y_treino)                        
y_pred=mlp.predict(X_teste)                        
print(y_pred)                                    
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acurácia MLP:',accuracy)

[ 1  1  1 -1]
acurácia Perceptron: 1.0

[ 1  1  1 -1]
acurácia MLP: 1.0


# Segunda tarefa: E Binário
Utilize os dados e execute o Perceptron e o MLP, conforme o exemplo (4).

In [12]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[1, 
            0,
            0,
            0
           ]
X_teste=X_treino
y_teste=y_treino

ptn = Perceptron(max_iter=500,tol=0.001)                    
ptn.fit(X_treino, y_treino)                    
y_pred=ptn.predict(X_teste)                      
print(y_pred) 
accuracy=metric.accuracy_score(y_teste, y_pred, normalize=True)
print('acurácia Perceptron:',accuracy)    
print()

mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(3,3), activation='relu') 
mlp.fit(X_treino, y_treino)                        
y_pred=mlp.predict(X_teste)                        
print(y_pred)                                    
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acurácia MLP:',accuracy)

[1 0 0 0]
acurácia Perceptron: 1.0

[1 0 0 0]
acurácia MLP: 1.0


# Terceira tarefa: E Bipolar
Modifique os dados binários da segunda tarefa para dados bipolares. 
Utilize os dados e execute o Perceptron e o MLP.



In [13]:
X_treino=[[1, 1], 
            [1, -1],
            [-1, 1],
            [-1, -1]
           ]
y_treino=[1, 
            1,
            1,
            -1
           ]
X_teste=X_treino
y_teste=y_treino

ptn = Perceptron(max_iter=500,tol=0.001)                    
ptn.fit(X_treino, y_treino)                    
y_pred=ptn.predict(X_teste)                      
print(y_pred) 
accuracy=metric.accuracy_score(y_teste, y_pred, normalize=True)
print('acurácia Perceptron:',accuracy)    
print()

mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(3,3), activation='relu') 
mlp.fit(X_treino, y_treino)                        
y_pred=mlp.predict(X_teste)                        
print(y_pred)                                    
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acurácia MLP:',accuracy)

[ 1  1  1 -1]
acurácia Perceptron: 1.0

[ 1  1  1 -1]
acurácia MLP: 1.0


# Quarta tarefa: dois neurônios de saída
Utilize o MLP para treinar e predizer o seguinte dataset. O que você observou ? Interprete a resposta.

In [21]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[[1, 1], 
            [1, 1],
            [1, 1],
            [0, 1]
           ]
X_teste=X_treino
y_teste=y_treino

mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(5,2), activation='relu') 
mlp.fit(X_treino, y_treino)                        
y_pred=mlp.predict(X_teste)                        
print(y_pred)                                    
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acurácia MLP:',accuracy)
print('Após a terceira execução a predição ficou igual aos dados de treino, acredito exista uma falta de diversificação aos dados')

[[1 1]
 [1 1]
 [1 1]
 [0 1]]
acurácia MLP: 1.0
Após a terceira execução a predição ficou igual aos dados de treino, acredito exista uma falta de diversificação aos dados


# Quinta tarefa: XOR
Use o MLP para resolver o problema XOR Booleano. Como melhorar a acurácia? Qual configuração mínima de camadas escondidas é necessária para tornar a acurácia 1.0 (100% de acerto)?

In [87]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[1, 
            0,
            0,
            1
           ]
X_teste=X_treino
y_teste=y_treino

mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(6,6), activation='relu') 
mlp.fit(X_treino, y_treino)                        
y_pred=mlp.predict(X_teste)                        
print(y_pred)                                    
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acurácia MLP:',accuracy)
print('Para melhorar a acurácia podemos alterar as camadas escondidas.')
print('A configuração com (6,6) tornou a acurácia 1')

[1 0 0 1]
acurácia MLP: 1.0
Para melhorar a acurácia podemos alterar as camadas escondidas.
A configuração com (6,6) tornou a acurácia 1


# Sexta tarefa: Tautologia
Treine o MLP para resolver o problema da Tautologia binária. Observe o comportamento.

In [31]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[1, 
            1,
            1,
            1
           ]
X_teste=X_treino
y_teste=y_treino

mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(4,2), activation='relu') 
mlp.fit(X_treino, y_treino)                        
y_pred=mlp.predict(X_teste)                        
print(y_pred)                                    
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acurácia MLP:',accuracy)

# Sétima tarefa: XNOR
Use o MLP para resolver o problema XNOR Booleano. Como melhorar a acurácia? Qual configuração mínima de camadas escondidas é necessária para tornar a acurácia 1.0 (100% de acerto)?

In [85]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[0, 
            1,
            1,
            0
           ]
X_teste=X_treino
y_teste=y_treino

mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(6,8), activation='relu') 
mlp.fit(X_treino, y_treino)                        
y_pred=mlp.predict(X_teste)                        
print(y_pred)                                    
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acurácia MLP:',accuracy)
print('Para melhorar a acurácia podemos alterar as camadas escondidas.')
print('A configuração com (6,8) tornou a acurácia 1')

[0 1 1 0]
acurácia MLP: 1.0
Para melhorar a acurácia podemos alterar as camadas escondidas.
A configuração com (6,8) tornou a acurácia 1


# Oitava tarefa: Rede Neural com 3 entradas e 2 saídas
Experimente treinar os seguintes dados usando o MLP.  Altere o solver, as camadas escondidas e a função de ativação para melhorar a acurácia. 

In [84]:
X_treino=[[ 1,  1,  0], 
            [ 1, -1, -1],
            [-1,  1,  1],
            [-1, -1,  1],
            [ 0,  1, -1],
            [ 0, -1, -1],
            [ 1,  1,  1]
           ]
y_treino=[[1, 0], 
            [0, 1],
            [1, 1],
            [1, 0],
            [1, 0],
            [1, 1],
            [1, 1]
           ]
X_teste=X_treino
y_teste=y_treino

#altere o parâmetro solver do MLP: {'lbfgs', 'sgd', 'adam'}
#ealtere a função de ativação do MLP: {'identity', 'logistic', 'tanh', 'relu'}, default 'relu'

mlp = MLPClassifier(solver='adam', hidden_layer_sizes=(5,5), activation='tanh', max_iter=3000) 
mlp.fit(X_treino, y_treino)                        
y_pred=mlp.predict(X_teste)                        
print(y_pred)                                    
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acurácia MLP:',accuracy)

[[1 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]]
acurácia MLP: 1.0
